version: '3.3'

services:

    mindsdb:
        image: mindsdb/mindsdb
        container_name: mindsdb
        ports:
            - '47334:47334'
            - '47335:47335'
        restart: unless-stoppped

        