version: '3.3'

services:

    mindsdb:
        image: mindsdb/mindsdb
        container_name: mindsdb
        ports:
            - '8200:47334'
            - '8300:47335'
        restart: unless-stoppped

        
